<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\host\Nexora.WebApi\Nexora.WebApi.csproj" />
    <ProjectReference Include="..\..\contexts\resource-asset-management\Presentation\Nexora.Contexts.ResourceAssetManagement.Presentation.csproj" />
    <ProjectReference Include="..\..\contexts\resource-asset-management\Domain\Nexora.Contexts.ResourceAssetManagement.Domain.csproj" />
    <ProjectReference Include="..\..\contexts\identity-access-management\Presentation\Nexora.Contexts.IdentityAccessManagement.Presentation.csproj" />
    <ProjectReference Include="..\..\contexts\service-monitoring-intelligence\Domain\Nexora.Contexts.ServiceMonitoringIntelligence.Domain.csproj" />
    <ProjectReference Include="..\..\contexts\service-monitoring-intelligence\Presentation\Nexora.Contexts.ServiceMonitoringIntelligence.Presentation.csproj" />
  </ItemGroup>

</Project>
