using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nexora.Infrastructure.Migrations
{
    public partial class FixTenantRelation : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    -- Drop old tenant_groups table if it exists (from previous migration)
                    DROP TABLE IF EXISTS tenant_groups CASCADE;

                    -- Check if tenants table already exists (old schema)
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tenants') THEN
                        -- Drop old FK and index
                        IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_tenants_tenant_groups_tenant_group_id') THEN
                            ALTER TABLE tenants DROP CONSTRAINT FK_tenants_tenant_groups_tenant_group_id;
                        END IF;
                        DROP INDEX IF EXISTS IX_tenants_tenant_group_id;

                        -- Drop old column, add new one
                        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenants' AND column_name = 'tenant_group_id') THEN
                            ALTER TABLE tenants DROP COLUMN tenant_group_id;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenants' AND column_name = 'property_id') THEN
                            ALTER TABLE tenants ADD COLUMN property_id bigint NOT NULL DEFAULT 0;
                            ALTER TABLE tenants ALTER COLUMN property_id DROP DEFAULT;
                        END IF;

                        -- Add new FK if not exists
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_tenants_properties_property_id') THEN
                            ALTER TABLE tenants ADD CONSTRAINT FK_tenants_properties_property_id
                                FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE;
                        END IF;

                        CREATE INDEX IF NOT EXISTS IX_tenants_property_id ON tenants (property_id);
                    ELSE
                        -- Fresh create: tenants table (new schema)
                        CREATE TABLE tenants (
                            id bigint GENERATED BY DEFAULT AS IDENTITY,
                            property_id bigint NOT NULL,
                            user_id bigint,
                            first_name character varying(100) NOT NULL,
                            last_name character varying(100) NOT NULL,
                            country character varying(100) NOT NULL,
                            city character varying(100) NOT NULL,
                            address character varying(255) NOT NULL,
                            phone_number character varying(20),
                            created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT PK_tenants PRIMARY KEY (id),
                            CONSTRAINT FK_tenants_properties_property_id FOREIGN KEY (property_id)
                                REFERENCES properties (id) ON DELETE CASCADE,
                            CONSTRAINT FK_tenants_users_user_id FOREIGN KEY (user_id)
                                REFERENCES users (id) ON DELETE SET NULL
                        );

                        CREATE INDEX IX_tenants_property_id ON tenants (property_id);
                        CREATE UNIQUE INDEX IX_tenants_user_id ON tenants (user_id);
                    END IF;
                END
                $$");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    -- Drop new FK and index
                    DROP INDEX IF EXISTS IX_tenants_property_id;
                    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_tenants_properties_property_id') THEN
                        ALTER TABLE tenants DROP CONSTRAINT FK_tenants_properties_property_id;
                    END IF;

                    -- Drop new column
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenants' AND column_name = 'property_id') THEN
                        ALTER TABLE tenants DROP COLUMN property_id;
                    END IF;

                    -- Re-create tenant_groups table
                    CREATE TABLE IF NOT EXISTS tenant_groups (
                        id bigint GENERATED BY DEFAULT AS IDENTITY,
                        property_id bigint NOT NULL,
                        contract_start timestamp with time zone NOT NULL,
                        contract_end timestamp with time zone,
                        payment_status character varying(20) NOT NULL DEFAULT 'UpToDate',
                        is_active boolean NOT NULL DEFAULT TRUE,
                        created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT pk_tenant_groups PRIMARY KEY (id),
                        CONSTRAINT fk_tenant_groups_properties_property_id FOREIGN KEY (property_id)
                            REFERENCES properties (id) ON DELETE CASCADE
                    );
                    CREATE INDEX IF NOT EXISTS IX_tenant_groups_property_id ON tenant_groups (property_id);

                    -- Add back old column
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenants' AND column_name = 'tenant_group_id') THEN
                        ALTER TABLE tenants ADD COLUMN tenant_group_id bigint NOT NULL DEFAULT 0;
                    END IF;

                    -- Add back old FK and index
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_tenants_tenant_groups_tenant_group_id') THEN
                        ALTER TABLE tenants ADD CONSTRAINT FK_tenants_tenant_groups_tenant_group_id
                            FOREIGN KEY (tenant_group_id) REFERENCES tenant_groups (id) ON DELETE CASCADE;
                    END IF;
                    CREATE INDEX IF NOT EXISTS IX_tenants_tenant_group_id ON tenants (tenant_group_id);
                END
                $$");
        }
    }
}
