<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexora.Shared.Domain\Nexora.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\contexts\identity-access-management\Domain\Nexora.Contexts.IdentityAccessManagement.Domain.csproj" />
    <ProjectReference Include="..\..\contexts\resource-asset-management\Domain\Nexora.Contexts.ResourceAssetManagement.Domain.csproj" />
    <ProjectReference Include="..\..\contexts\service-execution-maintenance\Domain\Nexora.Contexts.ServiceExecutionMaintenance.Domain.csproj" />
    <ProjectReference Include="..\..\contexts\service-monitoring-intelligence\Domain\Nexora.Contexts.ServiceMonitoringIntelligence.Domain.csproj" />
    <ProjectReference Include="..\..\contexts\subscriptions-payment-management\Domain\Nexora.Contexts.SubscriptionsPaymentManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
  </ItemGroup>

</Project>
